baseURL = "https://jacob953.com"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0  International License."
languageCode = "en-us"
title = "JACO GARDEN"
theme = "hugo-three4th"
publishDir = "docs"

[author]
  name = "Jacob953"
  email = "i@jacob953.com"
  role = "Open-source Enthusiast, Curiosity-driven and Night owl"
  intro = "is ascending the mountain crest which dwarfs all peaks under his feet"

[params] 
  subscribe = true
  [[params.link]]
    name = "github"
    url = "https://github.com/Jacob953"
  [[params.link]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/junfeng-yu-578456248/"

[menu]
  [[menu.main]]
    name = "Garden"
    weight = 1
    url = "/"
    post = "caret-down"
  [[menu.main]]
    name = "Essays"
    url = "/essays"
    parent = "Garden"
    weight = 1
  [[menu.main]]
    name = "Cassette"
    url = "/cassette"
    weight = 2
  [[menu.main]]
    name = "Resume"
    url = "https://github.com/Jacob953/resume/blob/main/PDF/RESUME_WORK_EN.pdf"
    weight = 3
    post = "link"
